pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    blogpost-list-thumbnail:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 480
                                    height: 320
                                    positioning: center
                                    forceResize: true
                        medias: {  }
                        name: blogpost-list-thumbnail
                        description: ''
                        group: Blogpost
                        format: JPEG
                        quality: 70
                        highResolution: null
                        preserveColor: false
                        forceProcessICCProfiles: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1763401268
                        creationDate: 1755348069
                        preserveAnimation: false
