pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    heroImage:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 1920
                                    height: 1080
                                    positioning: center
                                    forceResize: true
                        medias: {  }
                        name: heroImage
                        description: ''
                        group: ''
                        format: JPEG
                        quality: 75
                        highResolution: null
                        preserveColor: false
                        forceProcessICCProfiles: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1763401319
                        creationDate: 1748524181
                        preserveAnimation: false
