pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    introAuthor:
                        items:
                            -
                                method: resize
                                arguments:
                                    width: 250
                                    height: 250
                        medias: {  }
                        name: introAuthor
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        forceProcessICCProfiles: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1762545192
                        creationDate: 1762545159
                        preserveAnimation: false
