pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    socialPreviewImage:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 1200
                                    height: 630
                                    positioning: center
                                    forceResize: true
                        medias: {  }
                        name: socialPreviewImage
                        description: ''
                        group: ''
                        format: JPEG
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        forceProcessICCProfiles: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1762643136
                        creationDate: 1762635656
                        preserveAnimation: false
