pimcore_seo:
    sitemaps:
        generators:
            app_blogposts:
                enabled: true
                priority: 50
                generator_id: App\Sitemap\BlogpostGenerator

            # Pimcore ships a default document tree generator which is enabled by default
            # but you can easily disable it here.
            pimcore_documents:
                enabled: false